//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Nullable<long> id { get; set; }
        public int user_id { get; set; }
        public string activity_type { get; set; }
        public System.DateTime date_time { get; set; }
        public Nullable<long> person_id { get; set; }
        public Nullable<long> edition_id { get; set; }
    
        public virtual Edition Edition { get; set; }
        public virtual Edition Edition1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual User User { get; set; }
    }
}
