//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAndmagazine
    {
        public long id { get; set; }
        public Nullable<long> edition_id { get; set; }
        public short publication_no { get; set; }
        public string publication_place { get; set; }
        public string publisher_name { get; set; }
    
        public virtual Edition Edition { get; set; }
        public virtual Edition Edition1 { get; set; }
    }
}
