//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAuthor
    {
        public long id { get; set; }
        public long author_id { get; set; }
        public long s_no { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Author Author1 { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual Publication Publication1 { get; set; }
    }
}
