//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Edition()
        {
            this.BookAndmagazines = new HashSet<BookAndmagazine>();
            this.BookAndmagazines1 = new HashSet<BookAndmagazine>();
            this.Dealings = new HashSet<Dealing>();
            this.Dealings1 = new HashSet<Dealing>();
            this.Activities = new HashSet<Activity>();
            this.Activities1 = new HashSet<Activity>();
        }
    
        public long edition_id { get; set; }
        public Nullable<long> segment_id { get; set; }
        public short edition_no { get; set; }
        public short publication_quantity { get; set; }
        public short publication_pages { get; set; }
        public Nullable<short> cd_quantity { get; set; }
        public string registration_date_type { get; set; }
        public int registration_year { get; set; }
        public int registration_month { get; set; }
        public int registration_day { get; set; }
        public string publication_date_type { get; set; }
        public int publication_year { get; set; }
        public Nullable<int> publication_month { get; set; }
        public Nullable<int> publication_day { get; set; }
        public short cupboard_no { get; set; }
        public short cell_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAndmagazine> BookAndmagazines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAndmagazine> BookAndmagazines1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealing> Dealings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealing> Dealings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities1 { get; set; }
        public virtual Segment Segment { get; set; }
        public virtual Segment Segment1 { get; set; }
    }
}
