//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryMISEntities : DbContext
    {
        public LibraryMISEntities()
            : base("name=LibraryMISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookAndmagazine> BookAndmagazines { get; set; }
        public virtual DbSet<BookAuthor> BookAuthors { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Dealing> Dealings { get; set; }
        public virtual DbSet<Edition> Editions { get; set; }
        public virtual DbSet<MonographAndThesi> MonographAndThesis { get; set; }
        public virtual DbSet<Newspaper> Newspapers { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thesis> Theses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<NewspaperReport> NewspaperReports { get; set; }
        public virtual DbSet<NotReturnedBook> NotReturnedBooks { get; set; }
        public virtual DbSet<TotalPublication> TotalPublications { get; set; }
    }
}
