//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonographAndThesi
    {
        public long monograph_thesis_id { get; set; }
        public Nullable<long> s_no { get; set; }
        public string supervisor_firstname { get; set; }
        public string supervisor_lastname { get; set; }
        public string student_registration_year { get; set; }
        public string student_graduation_year { get; set; }
        public Nullable<System.DateTime> defence_data { get; set; }
        public string mark { get; set; }
        public string graduation_period { get; set; }
    
        public virtual Publication Publication { get; set; }
        public virtual Publication Publication1 { get; set; }
    }
}
