//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newspaper
    {
        public long newspaper_id { get; set; }
        public string newspaper_name { get; set; }
        public string publisher_name { get; set; }
        public int quantity { get; set; }
        public string date_type { get; set; }
        public System.DateTime publication_date { get; set; }
        public System.DateTime registration_date { get; set; }
    }
}
