//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotReturnedBook
    {
        public string person_name { get; set; }
        public string university { get; set; }
        public string faculty { get; set; }
        public string phone_number { get; set; }
        public string publication_name { get; set; }
        public System.DateTime issue_date { get; set; }
    }
}
