//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long id { get; set; }
        public Nullable<long> person_id { get; set; }
        public short semester { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
