//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thesis
    {
        public long thesis_id { get; set; }
        public long s_no { get; set; }
        public string internal_conflict { get; set; }
        public string external_conflict { get; set; }
    
        public virtual Publication Publication { get; set; }
        public virtual Publication Publication1 { get; set; }
    }
}
